version: "3"
services:
       mongo:
             container_name: mongo
             image: mongo:latest
             restart: always
             volumes:
              - ~/mongo:/data/db
             ports:
               - '27017:27017'
       ivna:
           container_name: ivna
           image: vitthals/ivna
           restart: always
           build: .
           environment:
              - MONGO_URI=mongodb://mongo:27017/task-manager-api
           ports:
             - "8000:8000"
           links:
             - mongo
           depends_on:
             - mongo